<?php echo $this->doctype(); ?>

<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 - POS WEBMOB UNOESC'); ?>

    <?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/css/style.css')
    ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/js/jquery.min.js')
    ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

</head>
<body>
    <div class="container">
        <div class="header clearfix">
            <h3 class="text-muted"><a href="/">RestBeer</a></h3>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <?php echo $this->content; ?>
            </div>
        </div>

        <footer class="footer">
            <ul class="list-unstyled">
                <li>RestBeer - Trabalho Pós Graduação WebMob UNOESC/Chapecó</li>
                <li>Aluno: Marcelo Garbin</li>
            </ul>
        </footer>
    </div> <!-- /container -->
</body>
</html>
