<?php echo $this->form()->openTag($beerForm); ?>
<div class="form-group col-sm-offset-2">
    <?php echo $this->formRow($beerForm->get('name')); ?>
</div>

<div class="form-group col-sm-offset-2">
    <?php echo $this->formRow($beerForm->get('style')); ?>
</div>

<div class="form-group col-sm-offset-2">
    <?php echo $this->formRow($beerForm->get('img')); ?>
</div>

<?php if ($beerForm->has('id')): ?>
    <?php echo $this->formElement($beerForm->get('id')) ?>
<?php endif;?>

<div class="form-group col-sm-offset-2">
    <div class="col-sm-8">
        <?php echo $this->formElement($beerForm->get('send')) ?>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>
